### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/node-girls-website#8]

**Comment by iteles** [comment]
Commit 011f5a17efe59924f1de49875c87063ca6825e4e

**Comment by iteles** [comment]
Note: Had to add an an `id` to the footer to enable the html anchoring in the nav. 
This is because if I used `<a name="footer"/>`, materialize was processing this in a strange way and wrapping the 'Contact Us' section in an `a`, which of course wreaked havoc on the styling.

Adding an `id` was the least code-heavy way of achieving the effect.
